services:
    perform_spam.manager:
        class: Perform\SpamBundle\SpamManager

    perform_spam.form.type.honeypot:
        class: Perform\SpamBundle\Form\Type\HoneypotType
        arguments:
            - "@event_dispatcher"
        tags:
            - {name: form.type}

    perform_spam.checker.honeypot:
        class: Perform\SpamBundle\Checker\HoneypotChecker
        arguments:
            - "@request_stack"
        tags:
            - {name: kernel.event_listener, event: perform_spam.honeypot_caught, method: onHoneypotCaught}
            - perform_spam.form_checker
